name: Release Checklist
on:
  release:
    types: [published]

permissions:
  contents: read
  issues: write

jobs:
  create-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/templates/release_checklist.md