name: Style checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
